- name: gathering facts from webserver
  hosts: all
  tasks: 
  - name: collect os name
    debug:
      msg: "{{ansible_distribution}}"
  - name: collect ip address
    debug:
      msg: "{{ansible_default_ipv4}}"